version: 0.2
phases:
  pre_build:
    steps:
      - run: echo "🎉 The job was automatically triggered by a event."
      - run: ls
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: 'true'
          DEFAULT_BRANCH: main
  build:
    commands:
      - echo "Building..."
      - npm run build
